Repository Mike2020x/frontend-top-v29-hoteles, pull requests merged in 2023-07, with the labels that each got.

#66 feat: 🎇 pages home, login, notfound and components update
  package-lock.json
  package.json
  public/hotel-booking-mir.jpg
  public/hotel-booking-mir1.jpg
  public/hotel-booking-mir10.jpg
  public/hotel-booking-mir2.jpg
  public/hotel-booking-mir3.jpg
  public/hotel-booking-mir4.jpg
  public/hotel-booking-mir5.jpg
  public/hotel-booking-mir6.jpg
  public/hotel-booking-mir7.jpg
  public/hotel-booking-mir8.jpg
  public/hotel-booking-mir9.jpg
  src/components/Blog/Blog.jsx
  src/components/Blog/Blog.scss
  src/components/login/Login.jsx
  src/components/login/index.scss
  src/components/navbar/NavBar.jsx
  src/components/searchForm/SearchForm.jsx
  src/components/searchForm/index.scss
  src/components/subscriptionForm/SubscriptionForm.jsx
  src/components/subscriptionForm/index.scss
  src/pages/NotFound/NotFound.jsx
  src/pages/NotFound/index.scss
  src/pages/VerifyAccount/ForgotPassword.jsx
  src/pages/VerifyAccount/VerifyAccount.jsx
  src/pages/VerifyAccount/VerifyMessage.jsx
  src/pages/VerifyAccount/index.scss
  src/router/index.jsx
Labels: large, waiting-for-review

#67 feat: 🎇 inputs login and component roomcard
  src/components/Room/RoomCard.jsx
  src/components/Room/index.scss
  src/components/login/Login.jsx
  src/components/login/index.scss
  src/pages/HotelSingle/HotelSingle.jsx
  src/pages/HotelSingle/index.scss
  src/pages/VerifyAccount/VerifyMessage.jsx
Labels: large, waiting-for-review

#68 feat: improvement input login and component search form
  src/components/searchForm/index.scss
Labels: small, waiting-for-review

#69 feat: update input login
  src/components/login/Login.jsx
Labels: small, waiting-for-review

#70 feat: correction button form from input login
  src/components/login/Login.jsx
Labels: small, waiting-for-review

#71 feat: updating main from develop working login
  package-lock.json
  package.json
  public/hotel-booking-mir.jpg
  public/hotel-booking-mir1.jpg
  public/hotel-booking-mir10.jpg
  public/hotel-booking-mir2.jpg
  public/hotel-booking-mir3.jpg
  public/hotel-booking-mir4.jpg
  public/hotel-booking-mir5.jpg
  public/hotel-booking-mir6.jpg
  public/hotel-booking-mir7.jpg
  public/hotel-booking-mir8.jpg
  public/hotel-booking-mir9.jpg
  src/components/Blog/Blog.jsx
  src/components/Blog/Blog.scss
  src/components/Room/RoomCard.jsx
  src/components/Room/index.scss
  src/components/login/Login.jsx
  src/components/login/index.scss
  src/components/navbar/NavBar.jsx
  src/components/searchForm/SearchForm.jsx
  src/components/searchForm/index.scss
  src/components/subscriptionForm/SubscriptionForm.jsx
  src/components/subscriptionForm/index.scss
  src/pages/HotelSingle/HotelSingle.jsx
  src/pages/HotelSingle/index.scss
  src/pages/NotFound/NotFound.jsx
  src/pages/NotFound/index.scss
  src/pages/VerifyAccount/ForgotPassword.jsx
  src/pages/VerifyAccount/VerifyAccount.jsx
  src/pages/VerifyAccount/VerifyMessage.jsx
  src/pages/VerifyAccount/index.scss
  src/router/index.jsx
Labels: large, waiting-for-review

#72 feat: implement use reducer
  package-lock.json
  package.json
  src/components/Hotel/Hotel.jsx
  src/components/ListHotels/ListHotels.jsx
  src/components/ListHotels/calculateCost.jsx
  src/components/loading/Loading.jsx
  src/components/loading/index.scss
  src/components/login/Login.jsx
  src/components/searchForm/index.scss
  src/context/ContextLogin.jsx
  src/context/index.jsx
  src/main.jsx
  src/pages/HotelSingle/HotelSingle.jsx
Labels: large, waiting-for-review

#73 feat: 🎇 use reducer, component slider and hotel single working
  src/assets/images.js
  src/components/Hotel/Hotel.scss
  src/components/ListHotels/ListHotels.jsx
  src/components/ListHotels/fetchSearch.jsx
  src/components/searchForm/SearchForm.jsx
  src/components/slider/Slider.jsx
  src/components/slider/index.scss
  src/context/index.jsx
  src/main.jsx
  src/pages/HotelSingle/HotelSingle.jsx
  src/pages/HotelSingle/index.scss
Labels: large, waiting-for-review

#74 Feat/contact info component
  src/assets/images.js
  src/components/contactInfo/contactInfo.jsx
  src/components/contactInfo/index.scss
  src/pages/Home.jsx
  src/pages/HotelSingle/HotelSingle.jsx
Labels: small, waiting-for-review

#76 Feat/stripe config
  package-lock.json
  package.json
  src/components/checkoutForm/CheckoutForm.jsx
  src/components/checkoutForm/index.scss
  src/components/paymentOption/PaymentOption.jsx
  src/pages/checkoutPage/Checkout.jsx
Labels: medium, waiting-for-review

#78 feat: 🎇 improvement pages and components
  package-lock.json
  package.json
  public/google-map.jpg
  src/components/Blog/Blog.jsx
  src/components/Hotel/Hotel.scss
  src/components/Room/RoomCard.jsx
  src/components/Room/index.scss
  src/components/footer/Footer.jsx
  src/components/hotelMap/HotelMap.jsx
  src/components/hotelMap/index.scss
  src/components/loading/index.scss
  src/components/login/index.scss
  src/components/searchForm/SearchForm.jsx
  src/components/searchForm/index.scss
  src/components/slider/Slider.jsx
  src/components/subscriptionForm/SubscriptionForm.jsx
  src/components/subscriptionForm/index.scss
  src/main.scss
  src/pages/HotelSingle/HotelSingle.jsx
  src/pages/HotelSingle/index.scss
  src/pages/VerifyAccount/ForgotPassword.jsx
  src/pages/VerifyAccount/ForgotPassword.scss
  src/pages/VerifyAccount/index.scss
  src/router/index.jsx
Labels: large, waiting-for-review

#80 Update/changes
  src/components/Hotel/Hotel.jsx
  src/components/Hotel/Hotel.scss
  src/components/ListHotels/ListHotels.jsx
  src/components/ListHotels/ListHotels.scss
  src/components/ListOffers/ListOffers.jsx
  src/components/ListOffers/ListOffers.scss
  src/components/Offer/Offer.jsx
  src/components/Offer/Offer.scss
  src/components/Room/index.scss
  src/components/contactInfo/contactInfo.jsx
  src/components/contactInfo/index.scss
  src/components/loading/Loading.jsx
  src/components/loading/index.scss
  src/components/searchForm/index.scss
  src/components/slider/Slider.jsx
  src/components/slider/index.scss
  src/pages/HotelList/HotelList.jsx
  src/pages/HotelList/index.scss
  src/pages/HotelSingle/HotelSingle.jsx
  src/pages/HotelSingle/index.scss
Labels: large, waiting-for-review

#81 feat: update styles of search form
  src/components/searchForm/index.scss
Labels: small, waiting-for-review

#83 feat: update structure select - options in page hotel single
  src/pages/HotelSingle/HotelSingle.jsx
Labels: small, waiting-for-review

#84 feat: update styles in index of hotel single
  src/pages/HotelSingle/index.scss
Labels: medium, waiting-for-review

#85 feat: update styles of components room and cardroom
  src/components/Room/index.scss
Labels: small, waiting-for-review

#86 feat: update style height of pages forgot password
  src/pages/VerifyAccount/ForgotPassword.scss
Labels: small, waiting-for-review

#87 feat: ❇️ new changes implemented
  src/components/ListHotels/ListHotels.jsx
  src/components/Room/RoomCard.jsx
  src/components/checkoutForm/CheckoutForm.jsx
  src/components/checkoutForm/index.scss
  src/components/login/index.scss
  src/components/searchForm/index.scss
  src/pages/checkoutPage/Checkout.jsx
  src/pages/checkoutPage/Checkout.scss
Labels: medium, waiting-for-review

#89 feat: update styles of component Offer.scss
  src/components/Offer/Offer.scss
Labels: small, waiting-for-review

#90 feat: corrections styles
  src/components/Offer/Offer.jsx
  src/components/Offer/Offer.scss
  src/components/searchForm/index.scss
Labels: small, waiting-for-review

#91 feat: stripe config
  src/components/checkoutForm/CheckoutForm.jsx
  src/components/checkoutForm/index.scss
  src/pages/checkoutPage/Checkout.jsx
Labels: small, waiting-for-review

#92 feat: params contac info
  src/components/ListHotels/ListHotels.jsx
  src/components/contactInfo/contactInfo.jsx
  src/pages/HotelSingle/HotelSingle.jsx
Labels: small, waiting-for-review

#93 update main
  package-lock.json
  package.json
  public/google-map.jpg
  src/assets/images.js
  src/components/Blog/Blog.jsx
  src/components/Hotel/Hotel.jsx
  src/components/Hotel/Hotel.scss
  src/components/ListHotels/ListHotels.jsx
  src/components/ListHotels/ListHotels.scss
  src/components/ListHotels/calculateCost.jsx
  src/components/ListHotels/fetchSearch.jsx
  src/components/ListOffers/ListOffers.jsx
  src/components/ListOffers/ListOffers.scss
  src/components/Offer/Offer.jsx
  src/components/Offer/Offer.scss
  src/components/Room/RoomCard.jsx
  src/components/Room/index.scss
  src/components/checkoutForm/CheckoutForm.jsx
  src/components/checkoutForm/index.scss
  src/components/contactInfo/contactInfo.jsx
  src/components/contactInfo/index.scss
  src/components/footer/Footer.jsx
  src/components/hotelMap/HotelMap.jsx
  src/components/hotelMap/index.scss
  src/components/loading/Loading.jsx
  src/components/loading/index.scss
  src/components/login/Login.jsx
  src/components/login/index.scss
  src/components/paymentOption/PaymentOption.jsx
  src/components/paymentOption/index.scss
  src/components/searchForm/SearchForm.jsx
  src/components/searchForm/index.scss
  src/components/slider/Slider.jsx
  src/components/slider/index.scss
  src/components/subscriptionForm/SubscriptionForm.jsx
  src/components/subscriptionForm/index.scss
  src/context/ContextLogin.jsx
  src/context/index.jsx
  src/main.jsx
  src/main.scss
  src/pages/Home.jsx
  src/pages/HotelList/HotelList.jsx
  src/pages/HotelList/index.scss
  src/pages/HotelSingle/HotelSingle.jsx
  src/pages/HotelSingle/index.scss
  src/pages/VerifyAccount/ForgotPassword.jsx
  src/pages/VerifyAccount/ForgotPassword.scss
  src/pages/VerifyAccount/index.scss
  src/pages/checkoutPage/Checkout.jsx
  src/pages/checkoutPage/Checkout.scss
  src/router/index.jsx
Labels: large, waiting-for-review

#94 fix: :bug: replace env variable name
  src/components/ListHotels/ListHotels.jsx
  src/pages/HotelSingle/HotelSingle.jsx
Labels: small, waiting-for-review

#95 feat: :sparkles: add checkout styles
  src/components/ListHotels/ListHotels.jsx
  src/components/checkoutForm/CheckoutForm.jsx
  src/components/checkoutForm/index.scss
  src/pages/HotelSingle/HotelSingle.jsx
  src/pages/checkoutPage/Checkout.jsx
  src/pages/checkoutPage/Checkout.scss
Labels: small, waiting-for-review

#96 feat: :sparkles: update: changes in components
  src/components/ListHotels/ListHotels.jsx
  src/components/ListHotels/calculateCost.jsx
  src/components/Room/Room.jsx
  src/components/Room/RoomCard.jsx
  src/components/bookingSummary/BookingSummary.jsx
  src/components/bookingSummary/index.scss
  src/components/contactInfo/contactInfo.jsx
  src/components/contactInfo/index.scss
  src/components/slider/Slider.jsx
  src/pages/HotelSingle/HotelSingle.jsx
Labels: medium, waiting-for-review

#97 feat: 💯 updating changes in functional components
  src/components/ListHotels/ListHotels.jsx
  src/components/ListHotels/calculateCost.jsx
  src/components/Room/Room.jsx
  src/components/Room/RoomCard.jsx
  src/components/bookingSummary/BookingSummary.jsx
  src/components/bookingSummary/index.scss
  src/components/checkoutForm/CheckoutForm.jsx
  src/components/checkoutForm/index.scss
  src/components/contactInfo/contactInfo.jsx
  src/components/contactInfo/index.scss
  src/components/slider/Slider.jsx
  src/pages/HotelSingle/HotelSingle.jsx
  src/pages/checkoutPage/Checkout.jsx
  src/pages/checkoutPage/Checkout.scss
Labels: medium

#98 feat: :sparkles: add bookin summary changes
  src/components/bookingSummary/BookingSummary.jsx
  src/components/checkoutForm/CheckoutForm.jsx
  src/components/login/Login.jsx
Labels: small, waiting-for-review

#101 feat: :sparkles: add loggin code
  src/components/login/Login.jsx
  src/context/index.jsx
Labels: small, waiting-for-review

#105 feat: :sparkles: add changes
  src/components/bookingSummary/BookingSummary.jsx
  src/components/travelerInfo/TravelerInfo.jsx
  src/components/travelerInfo/index.scss
  src/pages/bookinSummaryPage/BookingSummaryPage.jsx
Labels: medium, waiting-for-review

#107 feat: redirect to success page
  src/components/bookingSuccess/BookingSuccess.jsx
  src/components/bookingSuccess/index.scss
  src/components/bookingSummary/BookingSummary.jsx
  src/components/checkoutForm/CheckoutForm.jsx
  src/components/navbar/NavBar.jsx
Labels: medium, waiting-for-review
